#pragma once
#include <functional>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <cstdarg>
#include <cstdarg>
#include <cstdio>
#include <memory>
#include <random>
#include <cstddef>
#include <iostream>
#include <pthread.h>
#include <omp.h>
#include <filesystem>
#include <fstream>
#include <ranges>
#include "utils/common.hpp"
